nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.4.cjs
# npmScopes:
#   react-native-google-signin:
#     npmRegistryServer: https://npm.pkg.github.com
#     npmAuthToken: '${NPM_TOKEN_GOOGLE_SIGN_IN}'
